import smtplib 

fd1 = open("G:\\WeatherMonitorig\\_out\\PuneWeatherData.csv","r")
filedata1 = fd1.readlines()
fd1.close()

fd2 = open("G:\\WeatherMonitorig\\_out\\BengaluruWeatherData.csv","r")
filedata2 = fd2.readlines()
fd2.close()

fd3 = open("G:\\WeatherMonitorig\\_out\\HyderabadWeatherData.csv","r")
filedata3 = fd3.readlines()
fd3.close()

# fd4 = open("G:\\WeatherMonitorig\\_out\\PuneWeatherData.csv","r")
# filedata4 = fd4.readlines()
# fd4.close()


Header = "Hello All,\n\nPlease Find weather update below.\n"

mydata1 = filedata1[-1].split(",")
TempData1 = '\nCity: {}\nState: {}\nTemp in celsius: {}\nTemp in fahrenheit: {}\nLast Upadated: {}\n'.format(mydata1[0], mydata1[1],mydata1[2],mydata1[3],mydata1[4])

mydata2 = filedata2[-1].split(",")
TempData2 = '\nCity: {}\nState: {}\nTemp in celsius: {}\nTemp in fahrenheit: {}\nLast Upadated: {}\n'.format(mydata2[0], mydata2[1],mydata2[2],mydata2[3],mydata2[4])

mydata3 = filedata3[-1].split(",")
TempData3 = '\nCity: {}\nState: {}\nTemp in celsius: {}\nTemp in fahrenheit: {}\nLast Upadated: {}\n'.format(mydata3[0], mydata3[1],mydata3[2],mydata3[3],mydata3[4])

# mydata4 = filedata4[-1].split(",")
# TempData4 = '\nCity: {}\nState: {}\nTemp in celsius: {}\nTemp in fahrenheit: {}\nLast Upadated: {}\n'.format(mydata4[0], mydata4[1],mydata4[2],mydata4[3],mydata4[4])

footer = "\nThanks,\n\nBR,\nShrinivas\n9309783499\n"
note = "\n\nNote : This is an autogenerated e-mail, please do not reply."
TempData = Header + TempData1 + TempData2 + TempData3 + footer + note

gmailaddress = "onemytestmail@gmail.com"
gmailpassword = "oojdbtbqvgpowrsq"
mailto = "shrinivasmahajan87@gmail.com"
SUBJECT = "Weather update for {}".format(mydata1[4])
message = 'Subject: {}\n\n{}'.format(SUBJECT, TempData)
mailServer = smtplib.SMTP('smtp.gmail.com' , 587)
mailServer.starttls()
mailServer.login(gmailaddress , gmailpassword)
mailServer.sendmail(gmailaddress, mailto , message)
print(" \nEmail Sent successfully to",mailto)
mailServer.quit()
